# Generated by Django 4.2 on 2024-07-05 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StationReadings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_measure", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "station_readings",
            },
        ),
        migrations.CreateModel(
            name="StationStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("0", "Teste"),
                            ("1", "Solar"),
                            ("2", "SL500"),
                            ("3", "DualBase"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="stations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "station_station",
            },
        ),
        migrations.CreateModel(
            name="StationSensors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "unit_measure",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sensors",
                        to="datadash.stationstation",
                    ),
                ),
            ],
            options={
                "db_table": "station_sensors",
            },
        ),
        migrations.CreateModel(
            name="StationReadingsSensors",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "data_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="readings_sensors",
                        to="datadash.stationreadings",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sensors_readings",
                        to="datadash.stationsensors",
                    ),
                ),
            ],
            options={
                "db_table": "station_readings_sensors",
            },
        ),
        migrations.AddField(
            model_name="stationreadings",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="readings",
                to="datadash.stationstation",
            ),
        ),
    ]
