# Generated by Django 4.2 on 2024-06-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datadash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationstation",
            name="type",
            field=models.CharField(
                choices=[
                    ("0", "Teste"),
                    ("1", "Solar"),
                    ("2", "SL500"),
                    ("3", "DualBase"),
                ],
                default=0,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
