# Generated by Django 4.2 on 2024-07-02 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("datadash", "0002_stationstation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationreadings",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="readings",
                to="datadash.stationstation",
            ),
        ),
        migrations.AlterField(
            model_name="stationsensors",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sensors",
                to="datadash.stationstation",
            ),
        ),
        migrations.AlterField(
            model_name="stationstation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="stations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
