# Generated by Django 4.2 on 2024-07-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datadash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sl500",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(blank=True, null=True)),
                ("mes", models.IntegerField(blank=True, null=True)),
                ("dia", models.IntegerField(blank=True, null=True)),
                ("hora", models.IntegerField(blank=True, null=True)),
                ("minuto", models.IntegerField(blank=True, null=True)),
                ("segundo", models.IntegerField(blank=True, null=True)),
                (
                    "dado1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dado2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dado3",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "dado4",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "dado5",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "dado6",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("dado7", models.IntegerField(blank=True, null=True)),
                ("dado8", models.IntegerField(blank=True, null=True)),
                ("dado9", models.IntegerField(blank=True, null=True)),
                ("dado10", models.IntegerField(blank=True, null=True)),
                (
                    "dado11",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "dado12",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "dado13",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "dado14",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "dado15",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "dado16",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "dado17",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "dado18",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dado19",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "dado20",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "dado21",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dado22",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("dado23", models.IntegerField(blank=True, null=True)),
                ("dado24", models.IntegerField(blank=True, null=True)),
                ("dado25", models.IntegerField(blank=True, null=True)),
                ("data_safe", models.DateTimeField()),
                ("local_date", models.DateTimeField()),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="datadash.stationstation",
                    ),
                ),
            ],
            options={
                "db_table": "sl500",
            },
        ),
        migrations.CreateModel(
            name="Sl500P",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dado_0", models.IntegerField()),
                ("dado_1", models.FloatField()),
                ("dado_2", models.FloatField()),
                ("dado_3", models.FloatField()),
                ("dado_4", models.FloatField()),
                ("dado_5", models.FloatField()),
                ("dado_6", models.IntegerField()),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sl500_dd.sl500"
                    ),
                ),
            ],
            options={
                "db_table": "sl500p",
            },
        ),
    ]
