# Generated by Django 4.2 on 2024-06-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datadash", "0002_stationstation_type"),
        ("sl500_dd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sl500",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="datadash.stationstation",
            ),
        ),
        migrations.AlterField(
            model_name="sl500",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sl500p",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
