# Generated by Django 4.2 on 2024-08-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datadash", "0001_initial"),
        ("sl500_dd", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sl500",
            unique_together={
                ("ano", "mes", "dia", "hora", "minuto", "segundo", "station")
            },
        ),
    ]
