# Generated by Django 4.2 on 2024-06-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sl500_dd", "0002_sl500_station_alter_sl500_id_alter_sl500p_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sl500p",
            name="dado_5",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
