# Generated by Django 4.2 on 2024-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sl500_dd", "0003_alter_sl500p_dado_5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sl500",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sl500p",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
